### ISSUE TITLE
Cannot slice shape tuple without assigning it to variable

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#1070]
Pyccel does not allow taking the slice `a.shape[:2]`, where `a` is a Numpy array. Hence the following code does not work

```python
import numpy as np

a = np.ones((5, 6, 7, 8))

(s0, s1) = a.shape[:2]
(s2, s3) = a.shape[2:]

print(s0, s1, s2, s3)
```

and it raises the error

```bash/fortran/c
$ pyccel test_tuple_indexing.py 
Traceback (most recent call last):
  File "/usr/local/bin/pyccel", line 33, in <module>
    sys.exit(load_entry_point('pyccel', 'console_scripts', 'pyccel')())
  File "$PYCCEL/pyccel/pyccel/commands/console.py", line 216, in pyccel
    execute_pyccel(filename,
  File "$PYCCEL/pyccel/pyccel/codegen/pipeline.py", line 217, in execute_pyccel
    parser.annotate(**settings)
  File "$PYCCEL/pyccel/pyccel/parser/parser.py", line 164, in annotate
    parser = SemanticParser(self._syntax_parser,
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 200, in __init__
    self.annotate()
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 248, in annotate
    ast = self._visit(ast, **settings)
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 1625, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 1637, in _visit_Module
    body = self._visit(expr.program).body
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 1625, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 1800, in _visit_CodeBlock
    line = self._visit(b, **settings)
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 1625, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 2369, in _visit_Assign
    rhs = self._visit(rhs, **settings)
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 1625, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 1927, in _visit_IndexedElement
    return self._extract_indexed_from_var(var, args)
  File "$PYCCEL/pyccel/pyccel/parser/semantic.py", line 866, in _extract_indexed_from_var
    return var[indices[0]]
  File "$PYCCEL/pyccel/pyccel/ast/builtins.py", line 420, in __getitem__
    return self._args[i]
TypeError: tuple indices must be integers or slices, not Slice
```

The code works correctly if we add the assignment `s = a.shape` and then proceed to slice the tuple `s`. Interestingly, a similar error happens when we write `s3 = a.shape[-1]`, which raises the exception

```bash/fortran/c
TypeError: tuple indices must be integers or slices, not PyccelUnarySub
```

**Expected behavior**
It should be possible to slice directly `a.shape` without the need for a temporary tuple variable. 

**Language**
The error happens at the semantic stage, hence it does not depend on the target language.

**Comment by EmilyBourne** [comment]
It is interesting that it says that indices must be slices not Slices. Hopefully this is just a quick fix where the type check needs updating

**Comment by yguclu** [comment]
> It is interesting that it says that indices must be slices not Slices. Hopefully this is just a quick fix where the type check needs updating

This exception is raised by the Python interpreter. I think that we fail to process our own `Slice` objects

**Comment by yguclu** [comment]
Actually the problem is in [this if block](https://github.com/pyccel/pyccel/blob/1678a794f1c8edd09bb8b5e80b59443a1e99eae8/pyccel/parser/semantic.py#L863-L868):
```python
        if not isinstance(var, Variable):
            assert(hasattr(var,'__getitem__'))
            if len(indices)==1:
                return var[indices[0]]
            else:
                return self._visit(var[indices[0]][indices[1:]])
```
which we enter in the case of `s1, s2 = a.shape[:2]` because `a.shape` is a `Tuple` but not a `Variable`. We do not enter this piece of code in the case of `s = a.shape; s1, s2 = s[:2]`because `s` is a `HomogeneousTupleVariable`.
