### ISSUE TITLE
Can not import two files that import the same file

### ISSUE THREAD

**Issue by saidctb** [pyccel/pyccel#1110]
I have a folder with 4 Python files with the following dependencies
![image](https://user-images.githubusercontent.com/11571079/167851723-c51d0f8e-d11d-4b00-b5d7-cba5372de7e4.png)

such that each file contains:

file1.py
```python
def hello_world():
    print("Hello World!")
```
fil2.py
```python
import file1 as f1
def hello_world():
    f1.hello_world()
```

fil3.py
```python
import file2 as f2
def hello_world():
    f2.hello_world()
```
and file4.py
```python
import file3 as f3
import file2 as f2

f2.hello_world()
f3.hello_world()
```
pyccelizing file4 gives the following error
```
Traceback (most recent call last):
  File "/home/said/.local/bin/pyccel", line 33, in <module>
    sys.exit(load_entry_point('pyccel', 'console_scripts', 'pyccel')())
  File "/home/said/phd/pyccel/pyccel/commands/console.py", line 255, in pyccel
    compiler_export_file = compiler_export_file)
  File "/home/said/phd/pyccel/pyccel/codegen/pipeline.py", line 238, in execute_pyccel
    parser.annotate(**settings)
  File "/home/said/phd/pyccel/pyccel/parser/parser.py", line 157, in annotate
    self._annotate_sons(verbose=verbose)
  File "/home/said/phd/pyccel/pyccel/parser/parser.py", line 243, in _annotate_sons
    p.annotate(**settings)
  File "/home/said/phd/pyccel/pyccel/parser/parser.py", line 163, in annotate
    **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 199, in __init__
    self.annotate()
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 247, in annotate
    ast = self._visit(ast, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 1411, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 1423, in _visit_Module
    body = self._visit(expr.program).body
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 1411, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 1600, in _visit_CodeBlock
    line = self._visit(b, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 1411, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 3531, in _visit_Import
    import_init = p.semantic_parser.ast.init_func if source_target not in container['imports'] else None
AttributeError: 'NoneType' object has no attribute 'ast'
```
This can be solved by changing the order of the import in file4
```python
import file2 as f2
import file3 as f3

f2.hello_world()
f3.hello_world()
```

**Comment by EmilyBourne** [comment]
Please can you copy the error. I can only see the traceback

**Comment by saidctb** [comment]
this is the fill error message
![image](https://user-images.githubusercontent.com/11571079/167853026-86d0d644-f094-4756-831a-460756cf154b.png)
