### ISSUE TITLE
error when printing the minimum / maximum of an array of int

### ISSUE THREAD

**Issue by campospinto** [pyccel/pyccel#1376]
### Describe the bug

A Fortran runtime error occurs when printing the minimum value of an array of int
(I am not fully sure this is a bug, but certainly a strange behaviour of the print function)

### To Reproduce
Provide code to reproduce the behavior:
```python
import numpy as np


def test_print_float():
    ii = np.zeros(shape=2)
    ii[:] = 1
    print(" ii = ", ii)
    a = np.amin(ii)
    print(a)
    print(np.amin(ii))

def test_print_int():
    ii = np.empty(shape=2, dtype='int')
    ii[:] = 1
    print(" ii = ", ii)
    a = np.amin(ii)    
    if a == np.amin(ii):
        print('OK')
    else:
        print('NOT OK')
    print(a)
    print(np.amin(ii))
```

### Error details
The generated fortran function is 
```fortran
module debug_pyccel_module


  use, intrinsic :: ISO_C_Binding, only : f64 => C_DOUBLE , i64 => &
        C_INT64_T
  use, intrinsic :: ISO_FORTRAN_ENV, only : stdout => output_unit
  implicit none

  contains

  !........................................
  subroutine test_print_float() 

    implicit none

    real(f64), allocatable :: ii(:)
    real(f64) :: a
    integer(i64) :: i

    allocate(ii(0:1_i64))
    ii = 0.0_f64
    ii(:) = 1_i64
    write(stdout, '(A A)', advance="no") ' ii = ' , ' '
    write(stdout, '(A)', advance="no") '['
    do i = 0_i64, 0_i64, 1_i64
      write(stdout, '(F0.12 A)', advance="no") ii(i) , ' '
    end do
    write(stdout, '(F0.12 A)', advance="no") ii(1_i64) , ']'
    write(stdout, '()', advance="yes") 
    a = minval(ii)
    write(stdout, '(F0.12)', advance="yes") a
    write(stdout, '(F0.12)', advance="yes") minval(ii)
    if (allocated(ii)) then
      deallocate(ii)
    end if

  end subroutine test_print_float
  !........................................

  !........................................
  subroutine test_print_int() 

    implicit none

    integer(i64), allocatable :: ii(:)
    integer(i64) :: a
    integer(i64) :: i

    allocate(ii(0:1_i64))
    ii(:) = 1_i64
    write(stdout, '(A A)', advance="no") ' ii = ' , ' '
    write(stdout, '(A)', advance="no") '['
    do i = 0_i64, 0_i64, 1_i64
      write(stdout, '(I0 A)', advance="no") ii(i) , ' '
    end do
    write(stdout, '(I0 A)', advance="no") ii(1_i64) , ']'
    write(stdout, '()', advance="yes") 
    a = minval(Real(ii, f64))
    if (a == minval(Real(ii, f64))) then
      write(stdout, '(A)', advance="yes") 'OK'
    else
      write(stdout, '(A)', advance="yes") 'NOT OK'
    end if
    write(stdout, '(I0)', advance="yes") a
    write(stdout, '(I0)', advance="yes") minval(Real(ii, f64))
    if (allocated(ii)) then
      deallocate(ii)
    end if

  end subroutine test_print_int
  !........................................

end module debug_pyccel_module
```

The error message when running `test_print_int()` is
```sh
 ii =  [1 1]
OK
1
At line 65 of file debug_pyccel_module.f90 (unit = 6, file = 'stdout')
Fortran runtime error: Expected INTEGER for item 1 in formatted transfer, got REAL
(I0)
 ^
 ```

### Expected behavior
The print command `print(np.amin(ii))` should not give an error, but just print `1`
Note: the function `test_print_float()` yields no error.

### Language
Fortran

### Additional context
I am using pyccel 1.7.3 and python 3.11
The same error is obtained with np.min, np.amax and np.max

**Comment by EmilyBourne** [comment]
This problem arises at this line:
```
write(stdout, '(I0)', advance="yes") minval(Real(ii, f64))
```
because we declare that we are printing an integer but provide a real. The NumPy function `amin` (and the other mentioned functions) does indeed return an integer when called on an integer array and this output type is correctly set here:
https://github.com/pyccel/pyccel/blob/c2e58b930d0b5194708852ba237f59d01305e4da/pyccel/ast/numpyext.py#L1429-L1443
However this is quite uncommon in NumPy. Most functions (eg float) return floats. As a result the general printing function for NumPy functions casts integer arguments to floats to ensure the correct dtype:
https://github.com/pyccel/pyccel/blob/c2e58b930d0b5194708852ba237f59d01305e4da/pyccel/codegen/printing/fcode.py#L2720-L2730
This is causing the problem here.

However this is not the only problem. The function mentioned is `_print_NumpyUfuncBase`, however `amin`, `amax`, etc do not match the definition of a `ufunc` (https://numpy.org/doc/stable/reference/ufuncs.html). There are therefore a few corrections that should be made to fix this error:

**Acceptance Criteria**
- [ ] Change `_print_NumpyUfuncBase` so integer arguments are only cast if the result type is not integer (this problem also applies to actual `ufuncs`, eg `np.abs`)
- [ ] Change the super class for the functions in `pyccel/ast/numpyext.py` which do not fit the definition of `ufuncs` (these classes should inherit from `PyccelInternalFunction` but in order to reduce duplication it may be helpful to introduce a new superclass which inherits from `PyccelInternalFunction`)
- [ ] Ensure that the functions are correctly printed in Fortran, C and Python
- [ ] Ensure that there are existing tests for each of these functions
- [ ] Add at least one test reproducing the problem in the `tests/pyccel` folder

**Comment by campospinto** [comment]
Thanks @EmilyBourne for looking into this!

I have just noticed another printing problem with arrays, but I don't think this is related:
when pyccelizing the code 
```python
    A = np.zeros(2)
    print(np.abs(A))
```
I get the following error:
```
$ pyccel debug_pyccel_module.py
Traceback (most recent call last):
  File "/usr/local/bin/pyccel", line 8, in <module>
    sys.exit(pyccel())
             ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/commands/console.py", line 239, in pyccel
    execute_pyccel(filename,
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/pipeline.py", line 263, in execute_pyccel
    fname, prog_name = codegen.export(fname, language=language)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/codegen.py", line 205, in export
    code = self._printer.doprint(self.ast)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/codeprinter.py", line 52, in doprint
    lines = self._print(expr).splitlines(True)
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/fcode.py", line 456, in _print_Module
    body += '\n'.join(''.join([sep, self._print(i), sep]) for i in expr.funcs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/fcode.py", line 456, in <genexpr>
    body += '\n'.join(''.join([sep, self._print(i), sep]) for i in expr.funcs)
                                    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/fcode.py", line 1961, in _print_FunctionDef
    body_code = self._print(expr.body)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/fcode.py", line 1513, in _print_CodeBlock
    line = self._print(b)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyccel/codegen/printing/fcode.py", line 646, in _print_PythonPrint
    print_body = [FunctionCallArgument(f[for_index])]
                                       ~^^^^^^^^^^^
TypeError: 'NumpyAbs' object is not subscriptable
```
Shall I open a new issue ?
