### ISSUE TITLE
Can't assign a numpy array to multiple variables.

### ISSUE THREAD

**Issue by sboof911** [pyccel/pyccel#1414]
### Describe the bug
It is not possible to assign the result of a NumPy ufunc directly to multiple variables and the error raised includes a traceback instead of a user friendly message.

### To Reproduce
Provide code to reproduce the behavior:
```Python
if __name__ == "__main__":
     a, b = np.abs([1, -5])
```

### Error details
```Bash
Traceback (most recent call last):
  File "/home/pyccel-env/bin/pyccel", line 33, in <module>
    sys.exit(load_entry_point('pyccel', 'console_scripts', 'pyccel')())
  File "/home/changes/pyccel/commands/console.py", line 239, in pyccel
    execute_pyccel(filename,
  File "/home/changes/pyccel/codegen/pipeline.py", line 214, in execute_pyccel
    parser.annotate(**settings)
  File "/home/changes/pyccel/parser/parser.py", line 160, in annotate
    parser = SemanticParser(self._syntax_parser,
  File "/home/changes/pyccel/parser/semantic.py", line 235, in __init__
    self.annotate()
  File "/home/changes/pyccel/parser/semantic.py", line 308, in annotate
    ast = self._visit(ast)
  File "/home/changes/pyccel/parser/semantic.py", line 1598, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/changes/pyccel/parser/semantic.py", line 1610, in _visit_Module
    body = self._visit(expr.program).body
  File "/home/changes/pyccel/parser/semantic.py", line 1598, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/changes/pyccel/parser/semantic.py", line 1815, in _visit_CodeBlock
    line = self._visit(b)
  File "/home/changes/pyccel/parser/semantic.py", line 1598, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/changes/pyccel/parser/semantic.py", line 3010, in _visit_If
    args = [self._visit(i) for i in expr.blocks]
  File "/home/changes/pyccel/parser/semantic.py", line 3010, in <listcomp>
    args = [self._visit(i) for i in expr.blocks]
  File "/home/changes/pyccel/parser/semantic.py", line 1598, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/changes/pyccel/parser/semantic.py", line 2999, in _visit_IfSection
    body = self._visit(expr.body)
  File "/home/changes/pyccel/parser/semantic.py", line 1598, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/changes/pyccel/parser/semantic.py", line 1815, in _visit_CodeBlock
    line = self._visit(b)
  File "/home/changes/pyccel/parser/semantic.py", line 1598, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/changes/pyccel/parser/semantic.py", line 2606, in _visit_Assign
    for l, r in zip(lhs, rhs):
TypeError: 'NumpyAbs' object is not iterable
```

### Expected behavior
The assignation stage in the semantic should create a temporary variable allowing this object to be iterated.

### Language
Fortran and C

### Additional context
This issue is linked to this pull request: https://github.com/pyccel/pyccel/pull/1404

**Comment by VaradRengaraj** [comment]
Hi @EmilyBourne , you can assign me this. I will try to provide an implementation.
