### ISSUE TITLE
Unreadable Errors

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#157]
Many problems throw errors which are unreadable and do not help find the problem.

E.g. enumerate does not seem to be implemented it.
Using it throws the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyccel", line 11, in <module>
    load_entry_point('pyccel==0.1', 'console_scripts', 'pyccel')()
  File "/usr/local/lib/python3.5/dist-packages/pyccel/commands/console.py", line 244, in pyccel
    binary=binary)
  File "/usr/local/lib/python3.5/dist-packages/pyccel/codegen/utilities.py", line 179, in execute_pyccel
    code = codegen.doprint()
  File "/usr/local/lib/python3.5/dist-packages/pyccel/codegen/codegen.py", line 299, in doprint
    code = printer(self.expr)
  File "/usr/local/lib/python3.5/dist-packages/pyccel/codegen/printing/fcode.py", line 2121, in fcode
    return FCodePrinter(settings).doprint(expr, assign_to)
  File "/usr/local/lib/python3.5/dist-packages/pyccel/codegen/printing/codeprinter.py", line 60, in doprint
    lines = self._print(expr).splitlines()
  File "/home/emily/.local/lib/python3.5/site-packages/sympy/printing/printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyccel/codegen/printing/fcode.py", line 274, in _print_Program
    '{sep}\n').format(funcs=funcs, sep=sep, f=self._print(i))
  File "/home/emily/.local/lib/python3.5/site-packages/sympy/printing/printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyccel/codegen/printing/fcode.py", line 1216, in _print_FunctionDef
    body_code = '\n'.join(self._print(i) for i in body)
  File "/usr/local/lib/python3.5/dist-packages/pyccel/codegen/printing/fcode.py", line 1216, in <genexpr>
    body_code = '\n'.join(self._print(i) for i in body)
  File "/home/emily/.local/lib/python3.5/site-packages/sympy/printing/printer.py", line 257, in _print
    return getattr(self, printmethod)(expr, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pyccel/codegen/printing/fcode.py", line 1409, in _print_For
    itr_=Range(expr.iterable.element.shape[0])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by saidctb** [comment]
yes, indeed we need to improve our errors handling, we couldn't fix this  problem due to time constraint, we will  hopefully fix it as soon as possible in the near future
