### ISSUE TITLE
Wrong `numpy.sum` translation

### ISSUE THREAD

**Issue by saidctb** [pyccel/pyccel#1815]
In the following example
```python
import numpy as np
def f():
    return np.ones((10,10)).sum()
```
We get this generated code:
```fortran
  function f() result(Out_0001)

    implicit none

    real(f64) :: Out_0001

    Out_0001 = sum(1.0_f64)
    return

  end function f
```

**Comment by saidctb** [comment]
In C we get the following error
```bash
Traceback (most recent call last):
  File "/home/said/.local/bin/pyccel", line 8, in <module>
    sys.exit(pyccel())
  File "/home/said/phd/pyccel/pyccel/commands/console.py", line 266, in pyccel
    execute_pyccel(filename,
  File "/home/said/phd/pyccel/pyccel/codegen/pipeline.py", line 265, in execute_pyccel
    fname, prog_name = codegen.export(fname)
  File "/home/said/phd/pyccel/pyccel/codegen/codegen.py", line 227, in export
    code = self._printer.doprint(self.ast)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/codeprinter.py", line 52, in doprint
    lines = self._print(expr).splitlines(True)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/ccode.py", line 805, in _print_Module
    body    = ''.join(self._print(i) for i in expr.body)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/ccode.py", line 805, in <genexpr>
    body    = ''.join(self._print(i) for i in expr.body)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/ccode.py", line 1894, in _print_FunctionDef
    body  = self._print(expr.body)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/ccode.py", line 2209, in _print_CodeBlock
    code = self._print(b)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/ccode.py", line 2012, in _print_Return
    return code + 'return {};\n'.format(self._print(last_assign.rhs))
  File "/home/said/phd/pyccel/pyccel/codegen/printing/codeprinter.py", line 88, in _print
    obj = getattr(self, print_method)(expr)
  File "/home/said/phd/pyccel/pyccel/codegen/printing/ccode.py", line 1801, in _print_NumpySum
    raise TypeError(f'Expecting a NumpyArray, given {type(expr.arg)}')
TypeError: Expecting a NumpyArray, given <class 'pyccel.ast.numpyext.NumpyOnes'>
``

**Comment by saidctb** [comment]
> Is this a Fortran issue or a general issue?

It is a Fortran and C issue, Python translates it correctly

**Comment by yguclu** [comment]
@saidctb @EmilyBourne Is this issue still relevant?

**Comment by EmilyBourne** [comment]
Yes it seems to be. The problem is simply that:
- In Fortran we print `NumpyOnes` as `1` so you can do:
```python
a = np.ones((3,4))
```
and get:
```fortran
a(:,:) = 1.
```

- In C we get:

![Image](https://github.com/user-attachments/assets/75ec5885-1483-488b-8af9-24108415851f)

We should either create a temporary to store this or raise an error to ask the user to do this.

It is not a high priority issue as it only occurs when calling `sum` on a temporary array (i.e. an array for which the result is known).
