### ISSUE TITLE
Broken translation

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1853]
### Describe the bug
The translation of one of the files in the `quickstart.md` is broken. The problem occurs when wrapping the Fortran translation.

### To Reproduce
Provide code to reproduce the behaviour:
```python
def matmul(a: 'float[:,:](order=C)',
           b: 'float[:,:](order=F)',
           c: 'float[:,:](order=C)'):

    m, p = a.shape
    q, n = b.shape
    r, s = c.shape

    if p != q or m != r or n != s:
        return -1

    for i in range(m):
        for j in range(n):
            c[i, j] = 0.0
            for k in range(p):
                c[i, j] += a[i, k] * b[k, j]

    return 0
```

### Error details
When the module file is called `mod.py` the error is:
```bash/fortran/c
ERROR at shared library generation stage
Traceback (most recent call last):
  File "/home/emily/.local/bin/pyccel", line 8, in <module>
    sys.exit(pyccel())
  File "/home/emily/Code/pyccel/pyccel/commands/console.py", line 266, in pyccel
    execute_pyccel(filename,
  File "/home/emily/Code/pyccel/pyccel/codegen/pipeline.py", line 399, in execute_pyccel
    generated_filepath, shared_lib_timers = create_shared_library(codegen,
  File "/home/emily/Code/pyccel/pyccel/codegen/python_wrapper.py", line 179, in create_shared_library
    cwrap_ast = wrapper.wrap(c_ast)
  File "/home/emily/Code/pyccel/pyccel/codegen/wrapper/wrapper.py", line 79, in wrap
    return self._wrap(expr)
  File "/home/emily/Code/pyccel/pyccel/codegen/wrapper/wrapper.py", line 103, in _wrap
    return getattr(self, wrap_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/codegen/wrapper/c_to_python_wrapper.py", line 1080, in _wrap_BindCModule
    pymod = self._wrap_Module(expr)
  File "/home/emily/Code/pyccel/pyccel/codegen/wrapper/c_to_python_wrapper.py", line 1049, in _wrap_Module
    API_var, import_func = self._build_module_import_function(expr)
  File "/home/emily/Code/pyccel/pyccel/codegen/wrapper/c_to_python_wrapper.py", line 732, in _build_module_import_function
    AliasAssign(API_var, PyCapsule_Import(self.scope.get_python_name(mod_name))),
  File "/home/emily/Code/pyccel/pyccel/parser/scope.py", line 787, in get_python_name
    return self.parent_scope.get_python_name(name)
  File "/home/emily/Code/pyccel/pyccel/parser/scope.py", line 789, in get_python_name
    raise RuntimeError(f"Can't find {name} in scope")
RuntimeError: Can't find mod in scope
```

### Expected behavior
This should translate easily and the problematic behaviour should be caught by the tests

### Language
Fortran

**Comment by EmilyBourne** [comment]
It seems this has been broken since v1.9.0. I am not sure what makes this code special compared to other module tests that we have in `tests/pyccel`

**Comment by EmilyBourne** [comment]
This occurs because the filename is `mod` which is a Fortran keyword (used for modulo) so the module is renamed
