### ISSUE TITLE
Failing Python code

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1947]
### Describe the bug
The code below does not translate to C correctly. The error indicates that the booleans are not being translated to literals correctly. Further the shape parameter is not correctly called. It is not clear what causes this

### To Reproduce
Provide code to reproduce the behaviour:
```python
from numpy import zeros

def conditional_alloc(b1 : bool, b2 : bool):
    if b1:
        if b2:
            x = zeros(3, dtype=int)
            n = x.shape[0]
        else:
            n = 0
    else:
        x = zeros(4, dtype=int)
        n = x.shape[0]
    return n

if __name__ == '__main__':
    conditional_alloc(True,True)
    conditional_alloc(True,False)
    conditional_alloc(False,False)
```

### Error details
Provide the generated code, or the error message:
```bash/fortran/c
/home/emily/Code/pyccel/pyccel/codegen/compiling/compilers.py:505: UserWarning: /home/emily/Code/test/tmp/__pyccel__/tmp_bool_call.c: In function ‘conditional_alloc’:
/home/emily/Code/test/tmp/__pyccel__/tmp_bool_call.c:26:13: warning: implicit declaration of function ‘Shape’ [-Wimplicit-function-declaration]
   26 |         n = Shape(x, 0);
      |             ^~~~~

  warnings.warn(UserWarning(err))

ERROR at shared library generation stage
Traceback (most recent call last):
  File "/home/emily/.local/bin/pyccel", line 8, in <module>
    sys.exit(pyccel())
  File "/home/emily/Code/pyccel/pyccel/commands/console.py", line 266, in pyccel
    execute_pyccel(filename,
  File "/home/emily/Code/pyccel/pyccel/codegen/pipeline.py", line 401, in execute_pyccel
    generated_program_filepath = src_compiler.compile_program(compile_obj=prog_obj,
  File "/home/emily/Code/pyccel/pyccel/codegen/compiling/compilers.py", line 403, in compile_program
    self.run_command(cmd, verbose)
  File "/home/emily/Code/pyccel/pyccel/codegen/compiling/compilers.py", line 503, in run_command
    raise RuntimeError(err_msg)
RuntimeError: Failed to build module
/home/emily/Code/test/tmp/__pyccel__/prog_tmp_bool_call.c: In function ‘main’:
/home/emily/Code/test/tmp/__pyccel__/prog_tmp_bool_call.c:11:36: error: ‘True’ undeclared (first use in this function); did you mean ‘true’?
   11 |     Dummy_0000 = conditional_alloc(True, True);
      |                                    ^~~~
      |                                    true
/home/emily/Code/test/tmp/__pyccel__/prog_tmp_bool_call.c:11:36: note: each undeclared identifier is reported only once for each function it appears in
/home/emily/Code/test/tmp/__pyccel__/prog_tmp_bool_call.c:12:42: error: ‘False’ undeclared (first use in this function); did you mean ‘false’?
   12 |     Dummy_0001 = conditional_alloc(True, False);
      |                                          ^~~~~
      |                                          false
```

### Language
C

### Additional context
This code is found in the leak tests

**Comment by EmilyBourne** [comment]
Cannot reproduce on devel branch
