### ISSUE TITLE
Tanh from numpy not implemented

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#201]
The following code fails with "NotImplementedError: TODO"

```
from pyccel.decorators import external

@external
def test_tanh():
    from numpy import tanh
    return tanh(2)

from pyccel.epyccel import epyccel

test2=epyccel(test_tanh)
test2()
```

**Comment by EmilyBourne** [comment]
Sinh and cosh are not implemented either. It is an easy fix as they exist in ast/numpyext.py but are just missing from parser/semantic.py.

Should we import the math_functions dictionary from ast/utilities.py in parser/semantic.py so the list doesn't need to be duplicated?

**Comment by saidctb** [comment]
yes we  need to improve the type inference mechanism so that we don’t duplicate function names, so I think a quick fix would be to import  the math functions dictionary as you suggested.

**Comment by yguclu** [comment]
@EmilyBourne Your example now works, if we replace `tanh(2)` with `tanh(2.0)`.
@saidctb Should we cast the integer `2` to the real `2.0` automatically?

**Comment by saidctb** [comment]
yes we always need to add the casting but we don’t have that mechanism yet

**Comment by yguclu** [comment]
Surprisingly `atan(0, 1)` works and correctly returns `0`...

**Comment by EmilyBourne** [comment]
I have just run the test
```
from pyccel.epyccel import epyccel

def atan2_test():
    from numpy import arctan2
    print(arctan2(0.1))

test=epyccel(atan2_test)
test()
```

and the fortran code generated by epyccel is:
```
module f2py_mod_3k6ko3

implicit none




contains

!........................................
subroutine f2py_atan2_test()

  implicit none



  print *, 0
end subroutine
!........................................

end module
```

I assume sympy evaluates the expression immediately when numbers are provided. When variables are used instead:
```
from pyccel.epyccel import epyccel

def atan2_test():
    from numpy import arctan2
    a=0
    b=1
    print(arctan2(a, b))

test=epyccel(atan2_test)
test()
```

Then the code is translated as follows:
```
module f2py_mod_e007d9

implicit none




contains

!........................................
subroutine f2py_atan2_test()

  implicit none
  integer(kind=4) :: a
  integer(kind=4) :: b


  a = 0
  b = 1
  print *, atan(a/Real(b, 8))
end subroutine
!........................................

end module
```
Which avoids the casting problems but will cause problems if b=0

**Comment by yguclu** [comment]
Is this issue still relevant after PR [#322](https://github.com/pyccel/pyccel/pull/322)?

**Comment by EmilyBourne** [comment]
I think this issue needs to be recreated or renamed. Tanh has existed in pyccel for a while, however the casting problem that we discuss here still exists. If I run the original example I get the following error:
```
/home/emily/Code/test/tmp/__epyccel__/__pyccel__/mod_lt208w17.f90:17:20:

   Dummy_0040 = tanh(2_8)
                    1
Error: ‘x’ argument of ‘tanh’ intrinsic at (1) must be REAL or COMPLEX

ERROR at Fortran compilation stage
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    test2=epyccel(test_tanh)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/epyccel.py", line 197, in epyccel
    return epyccel_seq( inputs, **kwargs )
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/epyccel.py", line 123, in epyccel_seq
    output_name = module_name)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/pipeline.py", line 248, in execute_pyccel
    libs=libs)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/utilities.py", line 134, in compile_files
    output = subprocess.check_output(cmd, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'gfortran  -O3 -fPIC  -I"/home/emily/Code/test/tmp/__epyccel__/__pyccel__" -c   "/home/emily/Code/test/tmp/__epyccel__/__pyccel__/mod_lt208w17.f90" -o "/home/emily/Code/test/tmp/__epyccel__/__pyccel__/mod_lt208w17.o"  -J "/home/emily/Code/test/tmp/__epyccel__/__pyccel__"' returned non-zero exit status 1.
```

**Comment by yguclu** [comment]
Yes, this is actually a separate issue: several Fortran functions need casting to `real`, which we can add at the printing stage.

**Comment by yguclu** [comment]
I suggest we close this issue and create a new one.
