### ISSUE TITLE
Can't use multiple list comprehensions

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#2098]
### Describe the bug
Using multiple list comprehensions leads to errors

### To Reproduce
Provide code to reproduce the behaviour:
```python
def f(a : 'int[:]', n : int):
    a_slice = a[1:-1]
    period = 3.0
    lst_m = [ai-period for ai in a_slice]
    lst_p = [ai+period for ai in a_slice]
```

### Error details
Provide the generated code, or the error message:
```bash/fortran/c
Traceback (most recent call last):
  File "/home/emily/.local/bin/pyccel", line 8, in <module>
    sys.exit(pyccel())
  File "/home/emily/Code/pyccel/pyccel/commands/console.py", line 266, in pyccel
    execute_pyccel(filename,
  File "/home/emily/Code/pyccel/pyccel/codegen/pipeline.py", line 232, in execute_pyccel
    parser.annotate(verbose = verbose)
  File "/home/emily/Code/pyccel/pyccel/parser/parser.py", line 173, in annotate
    parser = SemanticParser(self._syntax_parser,
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 261, in __init__
    self.annotate()
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 318, in annotate
    ast = self._visit(ast)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2279, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2346, in _visit_Module
    self._visit(f)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2279, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 4239, in _visit_FunctionDef
    body = self._visit(expr.body)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2279, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2604, in _visit_CodeBlock
    line = self._visit(b)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2279, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 3381, in _visit_Assign
    rhs = self._visit(rhs)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2279, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 3746, in _visit_FunctionalFor
    stop.invalidate_node()
  File "/home/emily/Code/pyccel/pyccel/ast/basic.py", line 123, in invalidate_node
    _ = [ci.remove_user_node(self) for ci in c if not self._ignore(ci)]
  File "/home/emily/Code/pyccel/pyccel/ast/basic.py", line 123, in <listcomp>
    _ = [ci.remove_user_node(self) for ci in c if not self._ignore(ci)]
  File "/home/emily/Code/pyccel/pyccel/ast/basic.py", line 478, in remove_user_node
    assert user_node in self._user_nodes
AssertionError
```

### Language
Semantic problem

**Comment by EmilyBourne** [comment]
cc: @jalalium

**Comment by jalalium** [comment]
@EmilyBourne, The issue stems rather from this:
```python
import numpy as np

if __name__ == "__main__":
    a_slice = [1,2,3]
    period = 3.0
    lst_m = [ai-period for ai in a_slice]
    print(ai)
```

this works just fine with pyccel. Is invalidate_node the thing to use here?
