### ISSUE TITLE
Md_mod benchmark broken

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#2109]
### Describe the bug
The MD test case in the benchmarks is broken

### Error details
Provide the generated code, or the error message:
```bash/fortran/c
Traceback (most recent call last):
  File "/home/emily/.local/bin/pyccel", line 8, in <module>
    sys.exit(pyccel())
  File "/home/emily/Code/pyccel/pyccel/commands/console.py", line 266, in pyccel
    execute_pyccel(filename,
  File "/home/emily/Code/pyccel/pyccel/codegen/pipeline.py", line 232, in execute_pyccel
    parser.annotate(verbose = verbose)
  File "/home/emily/Code/pyccel/pyccel/parser/parser.py", line 173, in annotate
    parser = SemanticParser(self._syntax_parser,
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 261, in __init__
    self.annotate()
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 318, in annotate
    ast = self._visit(ast)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2279, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2346, in _visit_Module
    self._visit(f)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2279, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 4242, in _visit_FunctionDef
    body = self._visit(expr.body)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2279, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2604, in _visit_CodeBlock
    line = self._visit(b)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 2279, in _visit
    obj = getattr(self, annotation_method)(expr)
  File "/home/emily/Code/pyccel/pyccel/parser/semantic.py", line 3617, in _visit_AugAssign
    rhs.remove_user_node(test_node, invalidate = False)
  File "/home/emily/Code/pyccel/pyccel/ast/basic.py", line 478, in remove_user_node
    assert user_node in self._user_nodes
AssertionError
```

### Language
All languages

**Comment by EmilyBourne** [comment]
This issue seems to be fixed
