### ISSUE TITLE
Numpy's shape should support tuple unpacking

### ISSUE THREAD

**Issue by yguclu** [pyccel/pyccel#300]
Assume that we have imported function `shape` from `numpy` and that `a` is a 2D Numpy array. 
Two common instructions do not work in Pyccel. The first is
```
n1, n2 = shape(a)
```
which fails with error
```
Traceback (most recent call last):
  File "[ROOT_DIR]/pyccel/parser/semantic.py", line 236, in annotate
    ast = self._visit(ast, **settings)

   ...

  File "[ROOT_DIR]/pyccel/parser/semantic.py", line 2298, in _visit_Assign
    new_lhs.append( self._assign_lhs_variable(l, d_var.copy(), rhs[i], **settings) )
TypeError: 'Shape' object does not support indexing
```
And the second is 
```
s = shape(a)
n1, n2 = s
```
which fails with error
```
Traceback (most recent call last):
  File "[ROOT_DIR]/pyccel/parser/semantic.py", line 199, in annotate
    ast = self._visit(ast, **settings)

  ...

  File "[ROOT_DIR]/pyccel/parser/semantic.py", line 2262, in _visit_Assign
    new_lhs.append( self._assign_lhs_variable(l, d_var.copy(), rhs[i], **settings) )
TypeError: 'Variable' object does not support indexing
```
Since both examples are of common use in Python, they should work as expected.

**Comment by EmilyBourne** [comment]
This is fixed. This equally fixes the following syntax:
```
import numpy as np
a = np.array([1,2,3])
x,y,z = a
```
