### ISSUE TITLE
Pyccel exits without producing a readable error when using a non-implemented data type in C

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#388]
Pyccel exits without producing a readable error when using a non-implemented data type in C. This is due to the use of the dictionary `dtype_registry` in `pyccel/codegen/printing/ccode.py`.
E.g: the following code:
```
from pyccel.decorators import types

@types('bool')
def f(x):
    return x
```
produces the error:
```
Traceback (most recent call last):
  File "/home/emily/.local/bin/pyccel", line 11, in <module>
    load_entry_point('pyccel==0.9.11', 'console_scripts', 'pyccel')()
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/commands/console.py", line 251, in pyccel
    folder        = args.output)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/pipeline.py", line 170, in execute_pyccel
    fname = codegen.export(fname, language=language)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/codegen.py", line 258, in export
    code = self.doprint(**settings)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/codegen.py", line 247, in doprint
    code = printer(self.expr, parser=self.parser, **settings)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/printing/ccode.py", line 421, in ccode
    return CCodePrinter(settings).doprint(expr, assign_to)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/printing/codeprinter.py", line 60, in doprint
    lines = self._print(expr).splitlines()
  File "/home/emily/.local/lib/python3.6/site-packages/sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/printing/ccode.py", line 105, in _print_Module
    return '\n\n'.join(self._print(i) for i in expr.body)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/printing/ccode.py", line 105, in <genexpr>
    return '\n\n'.join(self._print(i) for i in expr.body)
  File "/home/emily/.local/lib/python3.6/site-packages/sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/printing/ccode.py", line 162, in _print_FunctionDef
    decs       = '\n'.join(self._print(i) for i in decs)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/printing/ccode.py", line 162, in <genexpr>
    decs       = '\n'.join(self._print(i) for i in decs)
  File "/home/emily/.local/lib/python3.6/site-packages/sympy/printing/printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/printing/ccode.py", line 115, in _print_Declare
    dtype = dtype_registry[(dtype, prec)]
KeyError: ('bool', 4)
```
when it should produce:
```
ERROR at code generation stage
pyccel: [codegen] 
 |fatal| Pyccel has encountered syntax that has not been implemented yet. Please create an issue at https://github.com/pyccel/pyccel/issues and provide a small example of your problem. Do not forget to specify your target language (bool)
```

This issue will be fixed when all the datatypes offered are correctly implemented (i.e. when issue #390 opened by @MenoIy is fixed)
Using the NativeDatatypes instead of a dictionary to print the datatype in C (see `pyccel/codegen/printing/fcode.py` for an example) should raise a `PYCCEL_RESTRICTION_TODO` automatically if the datatype is not yet implemented

**Comment by MenoIy** [comment]
When inspecting the 'bool' variable passed as argument :


```
from pyccel.decorators import types

@types(bool)
def func(x):
    return x

```

```
>>> code.routines[0].arguments[0].inspect()
>>> Variable
  name           = x
  dtype          = bool
  rank           = 0
  allocatable    = False
  shape          = ()
  cls_base       = None
  cls_parameters = None
  is_pointer     = False
  is_target      = False
  is_polymorphic = False
  is_optional    = False
```
and 
```
>>>code.routines[0].arguments[0].precision
4
```

The variable type is bool and the precision is **4**. but in dictionary **dtype_registry** **in pyccel/codegen/printing/ccode.py**
**{('bool', 1) : int}** the precision set for a boolean type is **1** . When the precision is set to 4 the code work fine but 
when working with Py_BuildValue we can't product a boolean type python object exemple :


```
x = False
y = func(x)
print(y , type(y))
print(type(x))

>>> 0 <class 'int'>
>>> <class 'bool'>

```

**Comment by EmilyBourne** [comment]
You are right. The bool case is trivial to fix. However the discussions about fixing it should be had in the relevant issue (#390). This issue concerns the lack of a neat error message

**Comment by EmilyBourne** [comment]
> Using the NativeDatatypes instead of a dictionary to print the datatype in C (see pyccel/codegen/printing/fcode.py for an example) should raise a PYCCEL_RESTRICTION_TODO automatically if the datatype is not yet implemented

This is not possible as an int with precision 4 (int) and an int with precision 8 (long) are not printed using the same keyword. As a result the dictionary is the easiest way to implement this.

In order to fix the issue we should test if the datatype is in the dictionary. If it is then we can access it (as we do now), if not we should raise a NotImplementedError
