### ISSUE TITLE
epyccel crashes when called in parallel

### ISSUE THREAD

**Issue by saidctb** [pyccel/pyccel#451]
**Describe the bug**
the epyccel function crashes when called in parallel

E.g

```
cat > test_epyccel.py
from pyccel.epyccel import epyccel
from mpi4py import MPI
comm = MPI.COMM_WORLD

def f():
    return 1

g = epyccel(f, comm=comm)
```
and when executed with  `mpirun -n 1 python3  test_epyccel.py`
it crashed with this error message

```
Traceback (most recent call last):
  File "test_epyccel.py", line 8, in <module>
    g = epyccel(f, comm=comm)
  File "/home/said/phd/pyccel/pyccel/epyccel.py", line 185, in epyccel
    fmod_path = os.path.abspath(fmod.__file__)
AttributeError: 'fortran' object has no attribute '__file__'
```

**Comment by yguclu** [comment]
This works correctly for modules, but not for functions. Clearly we forgot to add a unit test for it.
