### ISSUE TITLE
Math functions cannot be used in a C program

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#469]
**Describe the bug**
When using the `math.h` header file in C, a program must compiled with the math library

**To Reproduce**
Provide code to reproduce the behavior:
```python
a = 3
b = 72.5%a
```

The error message:
```bash
ERROR at Fortran compilation stage
Traceback (most recent call last):
  File "/home/emily/.local/bin/pyccel", line 11, in <module>
    load_entry_point('pyccel==0.9.12', 'console_scripts', 'pyccel')()
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/commands/console.py", line 251, in pyccel
    folder        = args.output)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/pipeline.py", line 251, in execute_pyccel
    libs=libs)
  File "/home/emily/.local/lib/python3.6/site-packages/pyccel/codegen/utilities.py", line 135, in compile_files
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'gcc  -O3 -fPIC  -I"/home/emily/Code/test/tmp/__pyccel__"  "/home/emily/Code/test/tmp/__pyccel__/test.c" -o "test"   ' returned non-zero exit status 1.
```

The command `gcc  -O3 -fPIC  -I"/home/emily/Code/test/tmp/__pyccel__"  "/home/emily/Code/test/tmp/__pyccel__/test.c" -o "test"` gives:
```
/tmp/ccgCq8nt.o: In function `main':
test.c:(.text.startup+0x15): undefined reference to `fmod'
collect2: error: ld returned 1 exit status
```

**Expected behavior**
The correct command is:
```
gcc  -O3 -fPIC  -I"/home/emily/Code/test/tmp/__pyccel__"  "/home/emily/Code/test/tmp/__pyccel__/test.c" -o "test" -lm
```
Pyccel should detect that this library is required and add it to the compile libraries

**Language**
C

**Comment by rakati** [comment]
I wondering why math functions passed the tests in PR 434.

**Comment by EmilyBourne** [comment]
The command for creating a shared library is more complicated than the command for compiling a program. The command (use `--verbose` to see this output) is:
```
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.6/test_wrapper.o build/temp.linux-x86_64-3.6/home/emily/Code/test/tmp/__pyccel__/test.o -o build/lib.linux-x86_64-3.6/test.cpython-36m-x86_64-linux-gnu.so
```
The options beginning with `-Wl` are linker flags. I am guessing that one of those flags includes the maths library
