### ISSUE TITLE
Give clear error message for x = [2,"two"]

### ISSUE THREAD

**Issue by Beliavsky** [pyccel/pyccel#609]
I don't expect pyccel to translate

```
x = [2,"two"]
print(x)
```

since Fortran arrays have elements of the same type, but it would be nice to have a message "lists must have elements of the same type" instead of 

```
Traceback (most recent call last):
  File "/usr/local/bin/pyccel", line 8, in <module>
    sys.exit(pyccel())
  File "/usr/local/lib/python3.8/dist-packages/pyccel/commands/console.py", line 235, in pyccel
    execute_pyccel(filename,
  File "/usr/local/lib/python3.8/dist-packages/pyccel/codegen/pipeline.py", line 152, in execute_pyccel
    parser.annotate(**settings)
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/parser.py", line 139, in annotate
    parser = SemanticParser(self._syntax_parser,
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/semantic.py", line 175, in __init__
    self.annotate()
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/semantic.py", line 210, in annotate
    ast = self._visit(ast, **settings)
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/semantic.py", line 738, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/semantic.py", line 775, in _visit_CodeBlock
    ls = [self._visit(i, **settings) for i in expr.body]
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/semantic.py", line 775, in <listcomp>
    ls = [self._visit(i, **settings) for i in expr.body]
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/semantic.py", line 738, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/semantic.py", line 1741, in _visit_Assign
    rhs = self._visit(rhs, **settings)
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/semantic.py", line 738, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/usr/local/lib/python3.8/dist-packages/pyccel/parser/semantic.py", line 765, in _visit_PythonList
    return PythonList(*ls, sympify=False)
  File "/usr/local/lib/python3.8/dist-packages/pyccel/ast/builtins.py", line 299, in __init__
    assert len(integers + reals + complexes) == 0
AssertionError
```

**Comment by saidctb** [comment]
list are not handled yet, we need to use linked list to handle them properly, you can instead use tuples for non homogenous types , and numpy arrays for homogenous types.
