### ISSUE TITLE
Numpy.linspace doesn't work.

### ISSUE THREAD

**Issue by MostafaMamouni** [pyccel/pyccel#771]
**Describe the bug**
Pyccel fails when using numpy.linspace in any data type, it might need some investigations.

**To Reproduce**
Provide code to reproduce the behavior:
```python
    @types('int')
    def test_int(start):
        from numpy import linspace, shape
        stop = start + 7
        NumberOfSamplesToGenerate = 7
        b = linspace(start, stop, NumberOfSamplesToGenerate)
        s = shape(b)
        return len(s), s[0], b[0], b[5]
```

Provide the generated code, or the error message:
```
TypeError: unsupported operand type(s) for -: 'LiteralInteger' and 'LiteralInteger'
```

**Expected behavior**
generate correct Fortran/C code.

**Language**
Fortran

**Additional context**
The tests are already in place in #719.

**Comment by EmilyBourne** [comment]
>TypeError: unsupported operand type(s) for -: 'LiteralInteger' and 'LiteralInteger'

This bug is easy to fix. It means that somewhere we are doing:
```
a - b
```
instead of:
```
PyccelMinus(a,b)
```
The backtrace of your error should tell you where this is happening

**Comment by EmilyBourne** [comment]
The error is [here](https://github.com/pyccel/pyccel/blob/master/pyccel/ast/numpyext.py#L474)

**Comment by nhamidn** [comment]
i get another error when trying with this python code:

```
import numpy as np
n = 500

xvalues = np.linspace(-2, 2, n)
```

this is te error :

```
 Traceback (most recent call last):
  File "/usr/local/bin/pyccel", line 33, in <module>
    sys.exit(load_entry_point('pyccel==1.0.0', 'console_scripts', 'pyccel')())
  File "/Users/mac/demo_pyccel/pyccel/pyccel/commands/console.py", line 243, in pyccel
    execute_pyccel(filename,
  File "/Users/mac/demo_pyccel/pyccel/pyccel/codegen/pipeline.py", line 247, in execute_pyccel
    parser.annotate(**settings)
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/parser.py", line 188, in annotate
    parser = SemanticParser(self._syntax_parser,
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 178, in __init__
    self.annotate()
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 214, in annotate
    ast = self._visit(ast, **settings)
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 807, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 843, in _visit_CodeBlock
    ls = [self._visit(i, **settings) for i in expr.body]
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 843, in <listcomp>
    ls = [self._visit(i, **settings) for i in expr.body]
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 807, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 1746, in _visit_Assign
    rhs = self._visit(rhs, **settings)
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 807, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 1093, in _visit_DottedName
    return self._handle_function(func, args, **settings)
  File "/Users/mac/demo_pyccel/pyccel/pyccel/parser/semantic.py", line 1275, in _handle_function
    expr = func(*args, **kwargs)
  File "/Users/mac/demo_pyccel/pyccel/pyccel/ast/numpyext.py", line 527, in __init__
    raise TypeError('Expecting valid args')
TypeError: Expecting valid args
```

**Comment by EmilyBourne** [comment]
Linspace only accepts arguments that are one of the following types:
- Variable
- IndexedElement
- LiteralFloat
- LiteralInteger

It should accept any `PyccelAstNode`
