### ISSUE TITLE
Python Min and Max builtin  functions don't work in Fortran and C

### ISSUE THREAD

**Issue by saidctb** [pyccel/pyccel#772]
the following example is not supported in both languages
```python
a = max(1,2)
b = min(4,5)
```
this is the error message that we get
```
Traceback (most recent call last):
  File "/home/said/.local/bin/pyccel", line 33, in <module>
    sys.exit(load_entry_point('pyccel', 'console_scripts', 'pyccel')())
  File "/home/said/phd/pyccel/pyccel/commands/console.py", line 258, in pyccel
    folder        = args.output)
  File "/home/said/phd/pyccel/pyccel/codegen/pipeline.py", line 247, in execute_pyccel
    parser.annotate(**settings)
  File "/home/said/phd/pyccel/pyccel/parser/parser.py", line 191, in annotate
    **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 172, in __init__
    self.annotate()
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 208, in annotate
    ast = self._visit(ast, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 801, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 837, in _visit_CodeBlock
    ls = [self._visit(i, **settings) for i in expr.body]
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 837, in <listcomp>
    ls = [self._visit(i, **settings) for i in expr.body]
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 801, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 1637, in _visit_Assign
    rhs = self._visit(rhs, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 801, in _visit
    obj = getattr(self, annotation_method)(expr, **settings)
  File "/home/said/phd/pyccel/pyccel/parser/semantic.py", line 1263, in _visit_FunctionCall
    F = pyccel_builtin_function(expr, args)
  File "/home/said/phd/pyccel/pyccel/ast/utilities.py", line 62, in builtin_function
    return dic[name](*args)
TypeError: __init__() takes 2 positional arguments but 3 were given
```

**Comment by EmilyBourne** [comment]
This is due to a difference in how the arguments are handled in `ast.builtins` and `ast.utilities`. In `ast.builtins` we have:
```
class PythonMax(PyccelInternalFunction):
    def __init__(self, x):
        if not isinstance(x, (list, tuple, PythonTuple, PythonList)):
            raise TypeError('Unknown type of  %s.' % type(x))
```
But in `ast.utilities` we create the object by doing:
```
PythonMax(*args)
```

The simplest solution is to change the `__init__` function of `PythonMax` to:
```
class PythonMax(PyccelInternalFunction):
    def __init__(self, *args):
        if len(x)==1:
            x=x[0]
        if not isinstance(x, (tuple, PythonTuple, PythonList)):
            raise TypeError('Unknown type of  %s.' % type(x))
```

Looking at the code I suspect the following additional classes have the same problem:
- PythonSum
- PythonAbs
