### ISSUE TITLE
Some simple code examples have broken in Fortran

### ISSUE THREAD

**Issue by mostafaMamoni** [pyccel/pyccel#810]
**To Reproduce**
Provide code to reproduce the behavior:
```python
def foo():
    return 1 + 2
print(foo())
```

Generated code of module and the program :
```fortran
module test

use, intrinsic :: ISO_C_BINDING

implicit none

contains

!........................................
function foo() result(Out_0001)

  implicit none

  integer(C_INT64_T) :: Out_0001

  Out_0001 = 1_C_INT64_T + 2_C_INT64_T
  return

end function foo
!........................................

end module test
```
```fortran
program prog_prog_test

use test, only: foo
use, intrinsic :: ISO_C_BINDING

implicit none

print *, foo()

end program prog_prog_test
```
The error message:
```
/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/prog_test.f90:3:15:

    3 | use test, only: foo
      |               1
Error: Symbol 'foo' referenced at (1) not found in module 'test'
/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/prog_test.f90:8:8:

    8 | print *, foo()
      |        1
Error: Function 'foo' at (1) has no IMPLICIT type
```

some other examples:
```fortran
def foo(a:int):
    return 1 + 2
print(foo(2))
```
```fortran
def foo():
    return 1 + 2
foo()
```

**Language**
Fortran.

**Comment by EmilyBourne** [comment]
I also cannot reproduce this bug. Can you provide more information?
- Branch
- Compiler version
- Output with --verbose mode (to see the compile commands)

The final example does not work as the result is unused

**Comment by mostafaMamoni** [comment]
- Branch : master

- Compiler:
   ```
   GNU Fortran (Homebrew GCC 10.2.0) 10.2.0
   Copyright (C) 2020 Free Software Foundation, Inc.
   This is free software; see the source for copying conditions.  There is NO
   warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
   ```

- Output with --verbose mode:
```
>>> treating :: /Users/mostafamamouni/Desktop/env-pyccel/my_tests/test.py
gfortran  -O3 -fPIC  -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" -c   "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.f90" -o "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.o"  -J"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__"
gfortran  -O3 -fPIC  -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" -c   "bind_c_test.f90" -o "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/bind_c_test.o"  -J"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__"
/Users/mostafamamouni/Desktop/env-pyccel/bin/python /Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/setup_test.py build
running build
running build_ext
building 'test' extension
creating build
creating build/temp.macosx-10.15-x86_64-3.8
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__ -I/Users/mostafamamouni/Desktop/env-pyccel/lib/python3.8/site-packages/numpy/core/include -I/Users/mostafamamouni/Desktop/env-pyccel/include -I/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/include/python3.8 -c test_wrapper.c -o build/temp.macosx-10.15-x86_64-3.8/test_wrapper.o -O3 -fPIC -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__"
creating build/lib.macosx-10.15-x86_64-3.8
clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk build/temp.macosx-10.15-x86_64-3.8/test_wrapper.o /Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/bind_c_test.o /Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.o -L/usr/local/Cellar/gcc/10.2.0/lib/gcc/10 -lgfortran -o build/lib.macosx-10.15-x86_64-3.8/test.cpython-38-darwin.so

> Shared library has been created: /Users/mostafamamouni/Desktop/env-pyccel/my_tests/test.cpython-38-darwin.so
gfortran  -O3 -fPIC  -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" -I"/Users/mostafamamouni/Desktop/env-pyccel/lib/python3.8/site-packages/numpy/core/include" -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" /Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.o "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/prog_test.f90" -o "prog_test"

ERROR at Fortran compilation stage
Traceback (most recent call last):
  File "/Users/mostafamamouni/Desktop/env-pyccel/bin/pyccel", line 33, in <module>
    sys.exit(load_entry_point('pyccel', 'console_scripts', 'pyccel')())
  File "/Users/mostafamamouni/Desktop/env-pyccel/pyccel/pyccel/commands/console.py", line 243, in pyccel
    execute_pyccel(filename,
  File "/Users/mostafamamouni/Desktop/env-pyccel/pyccel/pyccel/codegen/pipeline.py", line 420, in execute_pyccel
    compile_files(fname, f90exec, flags,
  File "/Users/mostafamamouni/Desktop/env-pyccel/pyccel/pyccel/codegen/utilities.py", line 150, in compile_files
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gfortran  -O3 -fPIC  -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" -I"/Users/mostafamamouni/Desktop/env-pyccel/lib/python3.8/site-packages/numpy/core/include" -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" /Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.o "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/prog_test.f90" -o "prog_test"  ' returned non-zero exit status 1.
   ```

**Comment by EmilyBourne** [comment]
I'm not sure why the compiler command contains numpy things. Can you try running:
```
gfortran  -O3 -fPIC  -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" /Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.o "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/prog_test.f90" -o "prog_test"
```

**Comment by EmilyBourne** [comment]
I cannot produce this with the same compiler:
```
GNU Fortran (GCC) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Can you try deleting all files in the `__pyccel__` folder except `test.f90` and `prog_test.f90` and running the following commands:
```
gfortran  -O3 -fPIC  -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" -c   "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.f90" -o "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.o"  -J"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__"
gfortran  -O3 -fPIC  -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" -I"/Users/mostafamamouni/Desktop/env-pyccel/lib/python3.8/site-packages/numpy/core/include" -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" /Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.o "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/prog_test.f90" -o "prog_test"
```

**Comment by mostafaMamoni** [comment]
> I cannot produce this with the same compiler:
> 
> ```
> GNU Fortran (GCC) 10.2.0
> Copyright (C) 2020 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> ```
> 
> Can you try deleting all files in the `__pyccel__` folder except `test.f90` and `prog_test.f90` and running the following commands:
> 
> ```
> gfortran  -O3 -fPIC  -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" -c   "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.f90" -o "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.o"  -J"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__"
> gfortran  -O3 -fPIC  -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" -I"/Users/mostafamamouni/Desktop/env-pyccel/lib/python3.8/site-packages/numpy/core/include" -I"/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__" /Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/test.o "/Users/mostafamamouni/Desktop/env-pyccel/my_tests/__pyccel__/prog_test.f90" -o "prog_test"
> ```

it works 👍.

**Comment by EmilyBourne** [comment]
Stranger and stranger. Does the example work with pyccel if you change the file name?

**Comment by mostafaMamoni** [comment]
it works for me by changing the file name from `test.py` to something else.

**Comment by saidctb** [comment]
I had a similar problems when I use the name `test.py` for a file

**Comment by EmilyBourne** [comment]
I have experienced problems importing files named `test.py` in python. This is because python has a [built-in module named test](https://docs.python.org/3/library/test.html). When importing python imports:
1. built-in modules
2. local modules
3. installed modules

As a result it does not import the `test.py` file. However I have never had this problem when compiling. Do you think there could be a similar problem in gfortran? @saidctb do you have the same behaviour as @mostafaMamoni where compiling manually succeeds but letting pyccel run the same commands fails with gfortran errors?

**Comment by saidctb** [comment]
this file compiles for me, but I can't import it

**Comment by EmilyBourne** [comment]
But you can run `prog_test` generated by pyccel? In that case you are just experiencing the python import collision that I mentioned above

**Comment by saidctb** [comment]
> But you can run `prog_test` generated by pyccel? In that case you are just experiencing the python import collision that I mentioned above

yes
