### ISSUE TITLE
not assigning the return value of a function yields an error

### ISSUE THREAD

**Issue by campospinto** [pyccel/pyccel#913]
**Describe the bug**
When a function returning a value is called but its returned value is not assigned, the compilation fails.

**To Reproduce**
This code works:
```python
def a() -> 'int':
    return 1

def b():
    c = a()
```
but this one gives an error compilation :
```python
def a() -> 'int':
    return 1

def b():
    a()
```

Provide the generated code, or the error message:
```bash/fortran/c
ERROR at Fortran compilation stage
Traceback (most recent call last):
  File "/Users/campos/Library/Python/3.9/bin/pyccel", line 33, in <module>
    sys.exit(load_entry_point('pyccel', 'console_scripts', 'pyccel')())
  File "/Users/campos/Work/codes/pyccel/pyccel/commands/console.py", line 240, in pyccel
    execute_pyccel(filename,
  File "/Users/campos/Work/codes/pyccel/pyccel/codegen/pipeline.py", line 423, in execute_pyccel
    compile_files(fname, f90exec, flags,
  File "/Users/campos/Work/codes/pyccel/pyccel/codegen/utilities.py", line 150, in compile_files
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT, shell=True)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'gfortran  -O3 -fPIC  -I"/Users/campos/Work/codes/fbl/fbsl_2d/particle_solvers/__pyccel__" -c   "/Users/campos/Work/codes/fbl/fbsl_2d/particle_solvers/__pyccel__/dummy.f90" -o "/Users/campos/Work/codes/fbl/fbsl_2d/particle_solvers/__pyccel__/dummy.o"  -J"/Users/campos/Work/codes/fbl/fbsl_2d/particle_solvers/__pyccel__"' returned non-zero exit status 1.
```

**Expected behavior**
The code should compile, or at least the error message should point to the "error". 

**Language**
Fortran

**Comment by EmilyBourne** [comment]
I cannot reproduce this error. I believe it is a duplicate of #896 which was fixed on 28th May. The latest release of pyccel (1.2.4) was released on 10th June so it should contain this fix. Can you confirm that you are using the latest version of pyccel?

**Comment by campospinto** [comment]
Indeed I was not using the latest version ! The error is solved, thanks. (I had looked for a similar error in the open issues, but forgot to do so in the closed ones...)
